language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

script:
  - docker --version # print the version for logging
  - docker tag udagram-api-feed wogayehu/udagram-api-feed:v1
  - docker tag udagram-api-user wogayehu/udagram-api-user:v1
  - docker tag udagram-frontend wogayehu/udagram-frontend:v1
  - docker tag udagram-reverseproxy wogayehu/udagram-reverseproxy:v1


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wogayehu/udagram-api-feed:v1
  - docker push wogayehu/udagram-api-user:v1
  - docker push wogayehu/udagram-frontend:v1
  - docker push wogayehu/udagram-reverseproxy:v1